### ISSUE TITLE
[Bug] chromeOptions is not a function (Windows)

### ISSUE THREAD

**Issue by fabiorzfreitas** [Izurii/modem-vivo-avancado#2]
Opa, achei o seu repo por [esse post no Reddit](https://www.reddit.com/r/InternetBrasil/comments/1cw6g2f/modo_bridge_vivo_fibra/)!

Antes de qualquer coisa, tentei no Windows 11, com Firefox-Dev como navegador padrão do sistema e Chrome com um perfil bem limpo pra coisas rápidas, que não precisem carregar minhas 300 abas. Rodei o script dentro de um environment isolado do Conda.

De toda forma, acho que esse contexto nem é relevante, já que é o mesmo erro que o /u/Spirited-Doughnut542 reportou no post:

```
C:\Users\Fabio\Desktop\modem-vivo-avancado\utils.js:73
    chromeOptions.setBinary(
                  ^

TypeError: chromeOptions.setBinary is not a function
    at Object.get_webdriver [as getWebDriver] (C:\Users\Fabio\Desktop\modem-vivo-avancado\utils.js:73:19)
    at C:\Users\Fabio\Desktop\modem-vivo-avancado\index.js:48:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

---

A propósito, eu tentei direto pelo seu script, amanhã ainda devo tentar fazer manualmente, depois via WSL e por último Live USB (Ventoy), mas o erro que tá dando por enquanto é esse!

**Comment by mbizzotto** [comment]
Ainda funciona em junho?

**Comment by fabiorzfreitas** [comment]
> Ainda funciona em junho?

Cara, recomendo que você acesse o post do Reddit que eu linkei, leia a parte relevante e tire as suas próprias conclusões

**Comment by mbizzotto** [comment]
Teria o link do seu post?
Obrigado

**Comment by mbizzotto** [comment]
Tentei rodar da erro
cannot find module 'selenium-webdriver'

**Comment by fabiorzfreitas** [comment]
@mbizzotto olha, você tá floodando o repo sem nem tentar descrever o seu ambiente, ou tentar fazer qualquer coisa a respeito antes. O link que você me pediu está na *primeira linha* aqui e o erro que você mencionou por último mostra que você não chegou nem a seguir os passos que estão na descrição.
